/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui;

import javax.swing.JOptionPane;
import model.Person;
import model.PersonDirectory;

/**
 *
 * @author mydel
 */
public class CreateJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ViewJPanels
     */
    PersonDirectory profile;

    public CreateJPanel(PersonDirectory person) {
        initComponents();
        this.profile = person;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitle = new javax.swing.JLabel();
        lblBAddress = new javax.swing.JLabel();
        lblName = new javax.swing.JLabel();
        lblDateOfBirth = new javax.swing.JLabel();
        lblTelephoneNumber = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        txtAddress = new javax.swing.JTextField();
        txtDateOfBirth = new javax.swing.JTextField();
        txtTelephoneNumber = new javax.swing.JTextField();
        btnSave = new javax.swing.JButton();
        lblFaxNumber = new javax.swing.JLabel();
        lbEmail = new javax.swing.JLabel();
        lblSSN = new javax.swing.JLabel();
        lblMRN = new javax.swing.JLabel();
        lblHPBN = new javax.swing.JLabel();
        lblBAN = new javax.swing.JLabel();
        lblCLN = new javax.swing.JLabel();
        txtBAN = new javax.swing.JTextField();
        txtHPBN = new javax.swing.JTextField();
        txtMRN = new javax.swing.JTextField();
        txtSSN = new javax.swing.JTextField();
        txtEmail = new javax.swing.JTextField();
        txtFN = new javax.swing.JTextField();
        lblVID = new javax.swing.JLabel();
        lblVSN = new javax.swing.JLabel();
        lblVLPN = new javax.swing.JLabel();
        lblDID = new javax.swing.JLabel();
        lblDSN = new javax.swing.JLabel();
        txtCLN = new javax.swing.JTextField();
        txtVID = new javax.swing.JTextField();
        txtVSN = new javax.swing.JTextField();
        txtVLPN = new javax.swing.JTextField();
        txtDID = new javax.swing.JTextField();
        txtDSN = new javax.swing.JTextField();
        txtLinkedInProfile = new javax.swing.JLabel();
        txtLinkedProfile = new javax.swing.JTextField();

        lblTitle.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitle.setText("Create Your Profile");

        lblBAddress.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblBAddress.setText("Address");

        lblName.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblName.setText("Name");

        lblDateOfBirth.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblDateOfBirth.setText("Date of birth");

        lblTelephoneNumber.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblTelephoneNumber.setText("Telephone Number");

        txtName.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        txtAddress.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtAddress.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAddressActionPerformed(evt);
            }
        });

        txtDateOfBirth.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        txtTelephoneNumber.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtTelephoneNumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTelephoneNumberActionPerformed(evt);
            }
        });

        btnSave.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnSave.setText("SAVE");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        lblFaxNumber.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblFaxNumber.setText("Fax Number");

        lbEmail.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lbEmail.setText("Email Address");

        lblSSN.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblSSN.setText("Social Security Number");

        lblMRN.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblMRN.setText("Medical Record Number");

        lblHPBN.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblHPBN.setText("Health Plan Beneficiary Number");

        lblBAN.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblBAN.setText("Bank Account Number");

        lblCLN.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblCLN.setText("Certificate/License Number");

        lblVID.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblVID.setText("Vehicle ID");

        lblVSN.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblVSN.setText("Vehicle Serial Number");

        lblVLPN.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblVLPN.setText("Vehicle License Plate Number");

        lblDID.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblDID.setText("Device  ID");

        lblDSN.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblDSN.setText("Device Serial Number");

        txtDSN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDSNActionPerformed(evt);
            }
        });

        txtLinkedInProfile.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtLinkedInProfile.setText("Linked Profile");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblName)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(lblBAddress)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblDateOfBirth)
                                    .addComponent(lblTelephoneNumber)
                                    .addComponent(lblFaxNumber)
                                    .addComponent(lbEmail)
                                    .addComponent(lblSSN)
                                    .addComponent(lblMRN)
                                    .addComponent(lblHPBN)
                                    .addComponent(lblBAN))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtBAN, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(txtHPBN)
                                        .addComponent(txtMRN)
                                        .addComponent(txtSSN)
                                        .addComponent(txtEmail)
                                        .addComponent(txtFN)
                                        .addComponent(txtTelephoneNumber, javax.swing.GroupLayout.DEFAULT_SIZE, 76, Short.MAX_VALUE)
                                        .addComponent(txtDateOfBirth, javax.swing.GroupLayout.DEFAULT_SIZE, 76, Short.MAX_VALUE)))))
                        .addGap(60, 60, 60)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnSave)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(lblDID)
                                    .addGap(159, 159, 159)
                                    .addComponent(txtDID, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(lblCLN)
                                    .addGap(54, 54, 54)
                                    .addComponent(txtCLN))
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(lblVID)
                                            .addGap(161, 161, 161))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                            .addComponent(lblVSN, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(64, 64, 64)))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(txtVLPN, javax.swing.GroupLayout.DEFAULT_SIZE, 90, Short.MAX_VALUE)
                                        .addComponent(txtVSN)
                                        .addComponent(txtVID))))
                            .addComponent(lblVLPN)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(txtLinkedInProfile, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGap(118, 118, 118)
                                    .addComponent(txtLinkedProfile, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(lblDSN)
                                    .addGap(88, 88, 88)
                                    .addComponent(txtDSN, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 96, Short.MAX_VALUE))
                    .addComponent(lblTitle, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 776, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(lblTitle)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblName)
                    .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblCLN)
                    .addComponent(txtCLN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtAddress, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblBAddress)
                        .addComponent(lblVID)
                        .addComponent(txtVID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDateOfBirth)
                    .addComponent(txtDateOfBirth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblVSN)
                    .addComponent(txtVSN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblVLPN)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblTelephoneNumber)
                        .addComponent(txtTelephoneNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtVLPN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblFaxNumber)
                    .addComponent(txtFN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblDID)
                    .addComponent(txtDID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbEmail)
                    .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblDSN)
                    .addComponent(txtDSN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSSN)
                    .addComponent(txtSSN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtLinkedInProfile)
                    .addComponent(txtLinkedProfile, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblMRN)
                    .addComponent(txtMRN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblHPBN)
                    .addComponent(txtHPBN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblBAN)
                    .addComponent(txtBAN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSave))
                .addContainerGap(38, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        // TODO add your handling code here:
        String name = txtName.getText();
        String address = txtAddress.getText();
        String dateOfBirth = txtDateOfBirth.getText();
        long telephoneNumber = Long.parseLong(txtTelephoneNumber.getText());
        long faxNumber = Long.parseLong(txtFN.getText());
        String EmailAddress = txtEmail.getText();
        String socialSecurityNumber = txtSSN.getText();
        int medicalRecordNumber = Integer.parseInt(txtMRN.getText());
        int healthPlanBeneficiaryNumber = Integer.parseInt(txtHPBN.getText());
        long bankAccountNumber = Long.parseLong(txtBAN.getText());
        String certificateOrlicenseNumber = txtCLN.getText();
        int vehicleId = Integer.parseInt(txtVID.getText());
        String vehicleSerialNumber = txtVSN.getText();
        String vechicleLicensePlates = txtVLPN.getText();
        int deviceId = Integer.parseInt(txtDID.getText());
        String deviceSerialNumber = txtDSN.getText();
        String linkedInId = txtLinkedInProfile.getText();

        Person p = profile.addProfile();
        p.setName(name);
        p.setAddress(address);
        p.setDateOfBirth(dateOfBirth);
        p.setTelephoneNumber(telephoneNumber);
        p.setFaxNumber(faxNumber);
        p.setEmailAddress(EmailAddress);
        p.setSocialSecurityNumber(socialSecurityNumber);
        p.setMedicalRecordNumber(medicalRecordNumber);
        p.setHealthPlanBeneficiaryNumber(healthPlanBeneficiaryNumber);
        p.setBankAccountNumber(bankAccountNumber);
        p.setCertificateOrlicenseNumber(certificateOrlicenseNumber);
        p.setVehicleId(vehicleId);
        p.setVehicleSerialNumber(vehicleSerialNumber);
        p.setVechicleLicensePlates(vechicleLicensePlates);
        p.setDeviceId(deviceId);
        p.setDeviceSerialNumber(deviceSerialNumber);
        p.setLinkedInId(linkedInId);

        JOptionPane.showMessageDialog(this, "Profile successfully created");

        txtName.setText("");
        txtAddress.setText("");
        txtDateOfBirth.setText("");
        txtTelephoneNumber.setText("");
        txtFN.setText("");
        txtEmail.setText("");
        txtSSN.setText("");
        txtMRN.setText("");
        txtHPBN.setText("");
        txtBAN.setText("");
        txtCLN.setText("");
        txtVID.setText("");
        txtVSN.setText("");
        txtVLPN.setText("");
        txtDID.setText("");
        txtDSN.setText("");
        txtLinkedInProfile.setText("");

    }//GEN-LAST:event_btnSaveActionPerformed

    private void txtAddressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAddressActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAddressActionPerformed

    private void txtTelephoneNumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTelephoneNumberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTelephoneNumberActionPerformed

    private void txtDSNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDSNActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDSNActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSave;
    private javax.swing.JLabel lbEmail;
    private javax.swing.JLabel lblBAN;
    private javax.swing.JLabel lblBAddress;
    private javax.swing.JLabel lblCLN;
    private javax.swing.JLabel lblDID;
    private javax.swing.JLabel lblDSN;
    private javax.swing.JLabel lblDateOfBirth;
    private javax.swing.JLabel lblFaxNumber;
    private javax.swing.JLabel lblHPBN;
    private javax.swing.JLabel lblMRN;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblSSN;
    private javax.swing.JLabel lblTelephoneNumber;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JLabel lblVID;
    private javax.swing.JLabel lblVLPN;
    private javax.swing.JLabel lblVSN;
    private javax.swing.JTextField txtAddress;
    private javax.swing.JTextField txtBAN;
    private javax.swing.JTextField txtCLN;
    private javax.swing.JTextField txtDID;
    private javax.swing.JTextField txtDSN;
    private javax.swing.JTextField txtDateOfBirth;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtFN;
    private javax.swing.JTextField txtHPBN;
    private javax.swing.JLabel txtLinkedInProfile;
    private javax.swing.JTextField txtLinkedProfile;
    private javax.swing.JTextField txtMRN;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtSSN;
    private javax.swing.JTextField txtTelephoneNumber;
    private javax.swing.JTextField txtVID;
    private javax.swing.JTextField txtVLPN;
    private javax.swing.JTextField txtVSN;
    // End of variables declaration//GEN-END:variables
}
