/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.Person;
import model.PersonDirectory;

/**
 *
 * @author mydel
 */
public class ViewJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ViewJPanel
     */
    PersonDirectory profile;

    public ViewJPanel(PersonDirectory profile) {
        initComponents();
        this.profile = profile;

        populateTable();
    }

    private void populateTable() {
        DefaultTableModel model = (DefaultTableModel) tblProfiles.getModel();
        model.setRowCount(0);

        for (Person person : profile.getProfiles()) {
            Object[] row = new Object[17];
            row[0] = person.getName();
            row[1] = person.getAddress();
            row[2] = person.getDateOfBirth();
            row[3] = person.getTelephoneNumber();
            row[4] = person.getFaxNumber();
            row[5] = person.getEmailAddress();
            row[6] = person.getSocialSecurityNumber();
            row[7] = person.getMedicalRecordNumber();
            row[8] = person.getHealthPlanBeneficiaryNumber();
            row[9] = person.getBankAccountNumber();
            row[10] = person.getCertificateOrlicenseNumber();
            row[11] = person.getVehicleId();
            row[12] = person.getVehicleSerialNumber();
            row[13] = person.getVechicleLicensePlates();
            row[14] = person.getDeviceId();
            row[15] = person.getDeviceSerialNumber();
            row[16] = person.getLinkedInId();

            model.addRow(row);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitle = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblProfiles = new javax.swing.JTable();
        btnView = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        lblVID = new javax.swing.JLabel();
        lblVSN = new javax.swing.JLabel();
        lblTelephoneNumber = new javax.swing.JLabel();
        lblVLPN = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        lblDID = new javax.swing.JLabel();
        txtAddress = new javax.swing.JTextField();
        lblDSN = new javax.swing.JLabel();
        txtDateOfBirth = new javax.swing.JTextField();
        txtCLN = new javax.swing.JTextField();
        txtTelephoneNumber = new javax.swing.JTextField();
        txtVID = new javax.swing.JTextField();
        txtVSN = new javax.swing.JTextField();
        lblFaxNumber = new javax.swing.JLabel();
        txtVLPN = new javax.swing.JTextField();
        txtDID = new javax.swing.JTextField();
        lbEmail = new javax.swing.JLabel();
        lblSSN = new javax.swing.JLabel();
        txtDSN = new javax.swing.JTextField();
        lblMRN = new javax.swing.JLabel();
        lblHPBN = new javax.swing.JLabel();
        lblBAN = new javax.swing.JLabel();
        lblCLN = new javax.swing.JLabel();
        txtBAN = new javax.swing.JTextField();
        txtHPBN = new javax.swing.JTextField();
        txtMRN = new javax.swing.JTextField();
        txtSSN = new javax.swing.JTextField();
        txtEmail = new javax.swing.JTextField();
        lblBAddress = new javax.swing.JLabel();
        txtFN = new javax.swing.JTextField();
        lblName = new javax.swing.JLabel();
        lblDateOfBirth = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        txtLinkedInProfile = new javax.swing.JTextField();

        lblTitle.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitle.setText("View Person Profile");

        tblProfiles.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Name", "Address", "Date Of Birth", "Telephone", "Fax", "Email", "SSN", "Medical Record No.", "Health Plan Beneficiary No.", "Bank Acc no.", "Certificate/license no.", "Vehicle ID", "Vehicle Serial no.", "Vehicle license no.", "Device ID", "Device Serial Number", "LinkedIn Profile"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblProfiles);

        btnView.setText("View");
        btnView.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewActionPerformed(evt);
            }
        });

        btnDelete.setText("Delete");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        lblVID.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblVID.setText("Vehicle ID");

        lblVSN.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblVSN.setText("Vehicle Serial Number");

        lblTelephoneNumber.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblTelephoneNumber.setText("Telephone Number");

        lblVLPN.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblVLPN.setText("Vehicle License Plate Number");

        txtName.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        lblDID.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblDID.setText("Device  ID");

        txtAddress.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtAddress.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAddressActionPerformed(evt);
            }
        });

        lblDSN.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblDSN.setText("Device Serial Number");

        txtDateOfBirth.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        txtTelephoneNumber.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtTelephoneNumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTelephoneNumberActionPerformed(evt);
            }
        });

        lblFaxNumber.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblFaxNumber.setText("Fax Number");

        lbEmail.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lbEmail.setText("Email Address");

        lblSSN.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblSSN.setText("Social Security Number");

        txtDSN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDSNActionPerformed(evt);
            }
        });

        lblMRN.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblMRN.setText("Medical Record Number");

        lblHPBN.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblHPBN.setText("Health Plan Beneficiary Number");

        lblBAN.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblBAN.setText("Bank Account Number");

        lblCLN.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblCLN.setText("Certificate/License Number");

        lblBAddress.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblBAddress.setText("Address");

        lblName.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblName.setText("Name");

        lblDateOfBirth.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblDateOfBirth.setText("Date of birth");

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel1.setText("Linked Profile");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jScrollPane1))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lblName)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addComponent(lblBAddress)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(txtAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lblDateOfBirth)
                                            .addComponent(lblTelephoneNumber)
                                            .addComponent(lblFaxNumber)
                                            .addComponent(lbEmail)
                                            .addComponent(lblSSN)
                                            .addComponent(lblMRN)
                                            .addComponent(lblHPBN)
                                            .addComponent(lblBAN))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtBAN, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtHPBN, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtMRN, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtSSN, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtFN, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtTelephoneNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtDateOfBirth, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 340, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                            .addComponent(lblDID, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(99, 99, 99)
                                            .addComponent(txtDID, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                            .addComponent(lblCLN)
                                            .addGap(54, 54, 54)
                                            .addComponent(txtCLN))
                                        .addGroup(layout.createSequentialGroup()
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                .addComponent(lblVSN, javax.swing.GroupLayout.DEFAULT_SIZE, 159, Short.MAX_VALUE)
                                                .addComponent(lblVID, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                            .addGap(64, 64, 64)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addComponent(txtVLPN)
                                                .addComponent(txtVSN)
                                                .addComponent(txtVID, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                    .addComponent(lblVLPN)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(lblDSN, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addGap(88, 88, 88)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(txtDSN, javax.swing.GroupLayout.DEFAULT_SIZE, 90, Short.MAX_VALUE)
                                            .addComponent(txtLinkedInProfile)))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(btnView)
                                .addGap(37, 37, 37)
                                .addComponent(btnDelete)))
                        .addGap(62, 62, 62))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(lblTitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnView)
                    .addComponent(btnDelete))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblName)
                    .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblCLN)
                    .addComponent(txtCLN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtAddress, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblBAddress)
                        .addComponent(lblVID)
                        .addComponent(txtVID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDateOfBirth)
                    .addComponent(txtDateOfBirth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblVSN)
                    .addComponent(txtVSN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblVLPN)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblTelephoneNumber)
                        .addComponent(txtTelephoneNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtVLPN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblFaxNumber)
                    .addComponent(txtFN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblDID)
                    .addComponent(txtDID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbEmail)
                    .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblDSN)
                    .addComponent(txtDSN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSSN)
                    .addComponent(txtSSN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(txtLinkedInProfile, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblMRN)
                    .addComponent(txtMRN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblHPBN)
                    .addComponent(txtHPBN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblBAN)
                    .addComponent(txtBAN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtAddressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAddressActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAddressActionPerformed

    private void txtTelephoneNumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTelephoneNumberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTelephoneNumberActionPerformed

    private void txtDSNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDSNActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDSNActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        // TODO add your handling code here:
        int selectedRowIndex = tblProfiles.getSelectedRow();
        if (selectedRowIndex <= 0) {
            JOptionPane.showMessageDialog(this, "Please select a row");
        }

        DefaultTableModel model = (DefaultTableModel) tblProfiles.getModel();
        Person selectedProfile = (Person) model.getValueAt(selectedRowIndex, 0);

        profile.deleteProfile(selectedProfile);

        JOptionPane.showMessageDialog(this, "Successfully deleted");

        populateTable();
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnViewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewActionPerformed
        // TODO add your handling code here:
        int selectedRowIndex = tblProfiles.getSelectedRow();
        if (selectedRowIndex <= 0) {
            JOptionPane.showMessageDialog(this, "Please select a row");
        }

        DefaultTableModel model = (DefaultTableModel) tblProfiles.getModel();
        Person selectedProfile = (Person) model.getValueAt(selectedRowIndex, 0);

        txtName.setText(selectedProfile.getName());
        txtAddress.setText(selectedProfile.getAddress());
        txtDateOfBirth.setText(selectedProfile.getDateOfBirth());
        txtTelephoneNumber.setText(String.valueOf(selectedProfile.getTelephoneNumber()));
        txtFN.setText(String.valueOf(selectedProfile.getFaxNumber()));
        txtEmail.setText(selectedProfile.getEmailAddress());
        txtSSN.setText(String.valueOf(selectedProfile.getSocialSecurityNumber()));
        txtMRN.setText(String.valueOf(selectedProfile.getMedicalRecordNumber()));
        txtHPBN.setText(String.valueOf(selectedProfile.getHealthPlanBeneficiaryNumber()));
        txtBAN.setText(String.valueOf(selectedProfile.getBankAccountNumber()));
        txtCLN.setText(selectedProfile.getCertificateOrlicenseNumber());
        txtVID.setText(String.valueOf(selectedProfile.getVehicleId()));
        txtVSN.setText(selectedProfile.getVehicleSerialNumber());
        txtVLPN.setText(selectedProfile.getVechicleLicensePlates());
        txtDID.setText(String.valueOf(selectedProfile.getDeviceId()));
        txtDSN.setText(selectedProfile.getDeviceSerialNumber());
        txtLinkedInProfile.setText(selectedProfile.getLinkedInId());
    }//GEN-LAST:event_btnViewActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnView;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbEmail;
    private javax.swing.JLabel lblBAN;
    private javax.swing.JLabel lblBAddress;
    private javax.swing.JLabel lblCLN;
    private javax.swing.JLabel lblDID;
    private javax.swing.JLabel lblDSN;
    private javax.swing.JLabel lblDateOfBirth;
    private javax.swing.JLabel lblFaxNumber;
    private javax.swing.JLabel lblHPBN;
    private javax.swing.JLabel lblMRN;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblSSN;
    private javax.swing.JLabel lblTelephoneNumber;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JLabel lblVID;
    private javax.swing.JLabel lblVLPN;
    private javax.swing.JLabel lblVSN;
    private javax.swing.JTable tblProfiles;
    private javax.swing.JTextField txtAddress;
    private javax.swing.JTextField txtBAN;
    private javax.swing.JTextField txtCLN;
    private javax.swing.JTextField txtDID;
    private javax.swing.JTextField txtDSN;
    private javax.swing.JTextField txtDateOfBirth;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtFN;
    private javax.swing.JTextField txtHPBN;
    private javax.swing.JTextField txtLinkedInProfile;
    private javax.swing.JTextField txtMRN;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtSSN;
    private javax.swing.JTextField txtTelephoneNumber;
    private javax.swing.JTextField txtVID;
    private javax.swing.JTextField txtVLPN;
    private javax.swing.JTextField txtVSN;
    // End of variables declaration//GEN-END:variables

}
